[workspace]
members = [
    # 精确匹配 - 避免匹配构建产物
    "The rust programming language/getting started/hello_cargo",

    # 多级通配符 - 匹配特定章节的所有项目
    "The rust programming language/common programming concepts/*",
    "The rust programming language/programming a guessing game/*",
    "The rust programming language/understanding ownership/*",
    "The rust programming language/using structs to structure related data/*"
]
resolver = "3"